#!/bin/sh /etc/rc.common

# shellcheck disable=SC2034
{
START=99
STOP=01
USE_PROCD=1
}

start_service() {
	_enabled=""
	_storage=""
	_filter=""
	_interface=""
	_host=""
	_port=""
	_direction=""
	_host=""
	_port=""
	_options=""
	config_load "system"

	config_get _enabled "system" tcp_dump ""
	[ "$_enabled" = "1" ] || return

	config_get _storage "system" tcp_mount ""
	config_get _filter "system" tcp_dump__filter ""
	config_get _interface "system" tcp_dump__interface ""
	config_get _host "system" tcp__host ""
	config_get _port "system" tcp__port ""
	config_get _direction "system" tcp_inout ""

	if [ "$_storage" = "/tmp" ]
	then
		_options="-C 5 -W 1"
	fi
	# Added a new _filter creation logic to make it work and be more readable
	if [ "$_host" != "" ] && [ "$_port" != "" ]
	then
			if [ "$_filter" != "" ]
			then
					_filter="$_filter and _host $_host and _port $_port"
			else
					_filter=" _host $_host and _port $_port"
			fi
	elif [ "$_host" != "" ] && [ "$_port" = "" ]
	then
			if [ "$_filter" != "" ]
			then
					_filter="$_filter and _host $_host"
			else
					_filter=" _host $_host"
			fi
	elif [ "$_host" = "" ] && [ "$_port" != "" ]
	then
			if [ "$_filter" != "" ]
			then
					_filter="$_filter and _port $_port"
			else
					_filter=" _port $_port"
			fi
	fi

	procd_open_instance
	procd_set_param command /usr/sbin/tcpdump
	procd_append_param command "$_options"
	[ -n "$_interface" ] && procd_append_param command -i "$_interface"
	[ -n "$_direction" ] && procd_append_param command -Q "$_direction"
	[ -n "$_filter" ] && procd_append_param command "$_filter"
	procd_append_param command -w "$_storage"/tcpdebug.pcap
	procd_set_param respawn
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "system"
}
