#!/bin/sh /etc/rc.common

START=99
STOP=1
USE_PROCD=1

start_service() {
    # shellcheck disable=SC3043
    {
    local enabled storage filter interface host port direction host port
    local OPTIONS=""
    }
    config_load "system"

    config_get enabled "system" tcp_dump ""
    [ "$enabled" = "1" ] || return

    config_get storage "system" tcp_mount ""
    config_get filter "system" tcp_dump_filter ""
    config_get interface "system" tcp_dump_interface ""
    config_get host "system" tcp_host ""
    config_get port "system" tcp_port ""
    config_get direction "system" tcp_inout ""

    if [ "$storage" = "/tmp" ]
    then
        OPTIONS="-C 5 -W 1"
    fi
    # Added a new filter creation logic to make it more readable
    if [ "$host" != "" ] && [ "$port" != "" ]; then
        if [ "$filter" != "" ]; then
            filter="$filter and host $host and port $port"
        else
            filter=" host $host and port $port"
        fi
    elif [ "$host" != "" ] && [ "$port" = "" ]; then
        if [ "$filter" != "" ]; then
            filter="$filter and host $host"
        else
            filter=" host $host"
        fi
    elif [ "$host" = "" ] && [ "$port" != "" ]; then
        if [ "$filter" != "" ]; then
            filter="$filter and port $port"
        else
            filter=" port $port"
        fi
    fi

    procd_open_instance
    COMMAND="/usr/sbin/tcpdump $OPTIONS -i $interface -Q $direction -w $storage/tcpdebug.pcap $filter"
    procd_set_param command "$COMMAND"
    procd_set_param respawn
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "system"
}
